version: '3.3'
services:

  qbittorrent:
    image: nevinee/qbittorrent:4.3.8
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai # 你的时区
      - UMASK_SET=022
      - WEBUI_PORT=8081 # 将此处修改成你欲使用的 WEB 管理平台端口
    volumes:
      - /root/vps/docker/qBittorrent/config:/config # 绝对路径请修改为自己的config文件夹
      - /mnt:/mnt # 绝对路径请修改为自己的downloads文件夹
    ports:
      # 要使用的映射下载端口与内部下载端口，可保持默认，安装完成后在管理页面仍然可以改成其他端口。
      - 6881:6881
      - 6881:6881/udp
      # 此处WEB UI 目标端口与内部端口务必保证相同，见问题1
      - 8081:8081
    restart: unless-stopped

  alist:
    image: 'xhofe/alist:latest'
    container_name: alist
    volumes:
        - '/root/vps/docker/alist:/alist/data'
    ports:
        - '5244:5244'
    restart: always

  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /root/vps/docker/plex/config:/config
      - /root/alist:/vol
        # - /path/to/tvseries:/tv
        # - /path/to/movies:/movies
    ports:
      - 32400:32400
    restart: unless-stopped

  emby:
    image: emby/embyserver
    container_name: embyserver
    network_mode: host # Enable DLNA and Wake-on-Lan
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /root/vps/docker/emby/config:/config # Configuration directory
      - /mnt:/mnt # Media directory
      - /root/alist:/mnt/alist
      - /path/to/movies:/mnt/share2 # Media directory
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped

  rec:
    image: bililive/recorder:latest
    container_name: recorder
    volumes:
        - '/mnt/Vol2/rec3:/rec'
    ports:
        - '2356:2356'
    restart: unless-stopped
